import type { AgentDefinition } from "./types"

export const presetSubagents: AgentDefinition[] = [
  {
    id: "explore",
    name: "Explore",
    description: "读取上下文、扫描项目结构、收集相关文件，不修改工作区。",
    tier: "subagent",
    origin: "system",
    visibility: "hidden",
    entryPolicy: "not-callable",
    delegationPolicy: "delegated-only",
    executorType: "ai-sdk",
    capabilities: ["context", "codebase-scan", "read-only"],
    allowedSubagents: [],
    allowedTools: ["ls", "read_file", "glob", "grep"],
    allowedSkills: [],
    permissionPolicy: {
      filesystem: "read",
      shell: "none",
      network: "none",
      deploy: "none",
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "general",
    name: "General",
    description: "处理轻量级推理、解释、摘要和重写任务。",
    tier: "subagent",
    origin: "system",
    visibility: "hidden",
    entryPolicy: "not-callable",
    delegationPolicy: "delegated-only",
    executorType: "ai-sdk",
    capabilities: ["reasoning", "summary", "rewrite"],
    allowedSubagents: [],
    allowedTools: [],
    allowedSkills: [],
    permissionPolicy: {
      filesystem: "none",
      shell: "none",
      network: "none",
      deploy: "none",
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "file",
    name: "File",
    description: "在审批边界内准备文件编辑、补丁和差异。",
    tier: "subagent",
    origin: "system",
    visibility: "hidden",
    entryPolicy: "not-callable",
    delegationPolicy: "delegated-only",
    executorType: "ai-sdk",
    capabilities: ["file-read", "file-write", "diff", "patch"],
    allowedSubagents: [],
    allowedTools: ["ls", "read_file", "glob", "grep", "write_file", "edit_file"],
    allowedSkills: [],
    permissionPolicy: {
      filesystem: "write",
      shell: "none",
      network: "none",
      deploy: "none",
    },
    enabled: true,
    readonly: true,
  },
]
