import type { AgentDefinition } from "./types"

const noAccess = {
  filesystem: "none",
  shell: "none",
  network: "none",
  deploy: "none",
  requiresApproval: false,
} as const

export const presetSubagents: AgentDefinition[] = [
  {
    id: "explore",
    name: "Explore",
    description: "Reads context, scans project structure, and gathers relevant files without changing the workspace.",
    tier: "subagent",
    origin: "system",
    visibility: "hidden",
    entryPolicy: "not-callable",
    delegationPolicy: "delegated-only",
    executorType: "mock",
    capabilities: ["context", "codebase-scan", "read-only"],
    allowedSubagents: [],
    allowedTools: ["ls", "read_file", "glob", "grep"],
    permissionPolicy: {
      filesystem: "read",
      shell: "none",
      network: "none",
      deploy: "none",
      requiresApproval: false,
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "general",
    name: "General",
    description: "Handles lightweight reasoning, explanation, summarization, and rewriting tasks.",
    tier: "subagent",
    origin: "system",
    visibility: "hidden",
    entryPolicy: "not-callable",
    delegationPolicy: "delegated-only",
    executorType: "mock",
    capabilities: ["reasoning", "summary", "rewrite"],
    allowedSubagents: [],
    allowedTools: [],
    permissionPolicy: noAccess,
    enabled: true,
    readonly: true,
  },
  {
    id: "file",
    name: "File",
    description: "Prepares file edits, patches, and diffs behind an approval boundary.",
    tier: "subagent",
    origin: "system",
    visibility: "hidden",
    entryPolicy: "not-callable",
    delegationPolicy: "delegated-only",
    executorType: "mock",
    capabilities: ["file-read", "file-write", "diff", "patch"],
    allowedSubagents: [],
    allowedTools: ["ls", "read_file", "glob", "grep"],
    permissionPolicy: {
      filesystem: "write",
      shell: "none",
      network: "none",
      deploy: "none",
      requiresApproval: true,
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "deploy",
    name: "Deploy",
    description: "Plans preview and publish actions while keeping deployment behind explicit approval.",
    tier: "subagent",
    origin: "system",
    visibility: "hidden",
    entryPolicy: "not-callable",
    delegationPolicy: "delegated-only",
    executorType: "mock",
    capabilities: ["preview", "deploy", "publish-status"],
    allowedSubagents: [],
    allowedTools: [],
    permissionPolicy: {
      filesystem: "read",
      shell: "limited",
      network: "limited",
      deploy: "publish",
      requiresApproval: true,
    },
    enabled: true,
    readonly: true,
  },
]

