import type { AgentDefinition, AgentRelation } from "./types"

const llmReadOnlyPolicy = {
  filesystem: "none",
  shell: "none",
  network: "none",
  deploy: "none",
  requiresApproval: false,
} as const

const orchestrationSubagents = ["explore", "general", "file", "deploy"]

export const presetAgents: AgentDefinition[] = [
  {
    id: "orchestrator",
    name: "Orchestrator",
    description: "Default entry agent that understands the task, chooses the right agents, and summarizes the final answer.",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "default",
    delegationPolicy: "can-delegate",
    executorType: "orchestrator",
    capabilities: ["routing", "planning", "delegation", "aggregation"],
    allowedSubagents: orchestrationSubagents,
    allowedTools: [],
    permissionPolicy: llmReadOnlyPolicy,
    enabled: true,
    readonly: true,
  },
  {
    id: "coder",
    name: "Coder",
    description: "Implements focused code changes and coordinates safe file edits through internal subagents.",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "can-delegate",
    executorType: "mock",
    capabilities: ["implementation", "refactor", "tests"],
    allowedSubagents: ["explore", "general", "file"],
    allowedTools: [],
    permissionPolicy: llmReadOnlyPolicy,
    enabled: true,
    readonly: true,
  },
  {
    id: "reviewer",
    name: "Reviewer",
    description: "Reviews code, plans, and diffs for correctness, regressions, and missing verification.",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "can-delegate",
    executorType: "mock",
    capabilities: ["code-review", "risk-analysis", "test-gaps"],
    allowedSubagents: ["explore", "general"],
    allowedTools: [],
    permissionPolicy: llmReadOnlyPolicy,
    enabled: true,
    readonly: true,
  },
  {
    id: "writer",
    name: "Writer",
    description: "Drafts product copy, technical notes, specs, and concise user-facing explanations.",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "can-delegate",
    executorType: "mock",
    capabilities: ["documentation", "copywriting", "summarization"],
    allowedSubagents: ["general"],
    allowedTools: [],
    permissionPolicy: llmReadOnlyPolicy,
    enabled: true,
    readonly: true,
  },
  {
    id: "planner",
    name: "Planner",
    description: "Breaks larger goals into scoped implementation plans, milestones, risks, and acceptance checks.",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "can-delegate",
    executorType: "mock",
    capabilities: ["planning", "architecture", "task-breakdown"],
    allowedSubagents: ["explore", "general"],
    allowedTools: [],
    permissionPolicy: llmReadOnlyPolicy,
    enabled: true,
    readonly: true,
  },
  {
    id: "opencode",
    name: "OpenCode",
    description: "External coding agent entry reserved for future OpenCode integration through the external adapter layer.",
    tier: "primary",
    origin: "external",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "terminal",
    executorType: "external-adapter",
    capabilities: ["external-agent", "coding", "workspace"],
    allowedSubagents: [],
    allowedTools: [],
    permissionPolicy: {
      filesystem: "write",
      shell: "limited",
      network: "limited",
      deploy: "none",
      requiresApproval: true,
    },
    external: {
      provider: "opencode",
      workingDirectoryPolicy: "runtime-workspace",
      configDirectoryPolicy: "runtime-managed",
      outputFormat: "event-stream",
    },
    enabled: true,
    readonly: true,
  },
]

export const presetAgentRelations: AgentRelation[] = [
  ...orchestrationSubagents.map((subagentId, index) => ({
    id: `orchestrator-to-${subagentId}`,
    fromAgentId: "orchestrator",
    toAgentId: subagentId,
    relationType: "can_delegate_to" as const,
    priority: 100 - index,
    enabled: true,
  })),
  ...["coder", "reviewer", "writer", "planner", "opencode"].map((agentId, index) => ({
    id: `orchestrator-to-${agentId}`,
    fromAgentId: "orchestrator",
    toAgentId: agentId,
    relationType: "can_delegate_to" as const,
    priority: 80 - index,
    enabled: true,
  })),
  {
    id: "coder-to-explore",
    fromAgentId: "coder",
    toAgentId: "explore",
    relationType: "can_delegate_to",
    taskTypes: ["codebase_scan", "context_lookup"],
    priority: 70,
    enabled: true,
  },
  {
    id: "coder-to-file",
    fromAgentId: "coder",
    toAgentId: "file",
    relationType: "can_delegate_to",
    taskTypes: ["edit", "patch", "diff"],
    priority: 69,
    enabled: true,
  },
  {
    id: "reviewer-to-explore",
    fromAgentId: "reviewer",
    toAgentId: "explore",
    relationType: "can_delegate_to",
    taskTypes: ["codebase_scan", "evidence_lookup"],
    priority: 60,
    enabled: true,
  },
  {
    id: "planner-to-general",
    fromAgentId: "planner",
    toAgentId: "general",
    relationType: "can_delegate_to",
    taskTypes: ["planning", "summarization"],
    priority: 50,
    enabled: true,
  },
]

