import type { AgentDefinition } from "./types"
import { DEFAULT_PRESET_BASH_PERMISSION_RULES } from "./bash-permission-rules"
import { presetAgentSystemPrompts } from "./preset-agent-prompts"

const orchestrationSubagents = ["explore", "general", "file", "deploy"]

export const presetAgents: AgentDefinition[] = [
  {
    id: "orchestrator",
    name: "Orchestrator",
    description: "默认入口智能体，负责理解任务、选择合适的智能体并汇总最终结果。",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "default",
    delegationPolicy: "can-delegate",
    executorType: "orchestrator",
    systemPrompt: presetAgentSystemPrompts.orchestrator,
    capabilities: ["routing", "planning", "delegation", "aggregation"],
    allowedSubagents: orchestrationSubagents,
    allowedTools: ["write_plan", "run_task", "web_fetch", "bash"],
    permissionPolicy: {
      filesystem: "none",
      shell: "limited",
      network: "full",
      deploy: "none",
    },
    toolPermissionRules: {
      bash: DEFAULT_PRESET_BASH_PERMISSION_RULES,
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "coder",
    name: "Coder",
    description: "专注于代码变更实现，通过内部子智能体协调安全的文件编辑。",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "can-delegate",
    executorType: "ai-sdk",
    systemPrompt: presetAgentSystemPrompts.coder,
    capabilities: ["implementation", "refactor", "tests"],
    allowedSubagents: ["explore", "general", "file"],
    allowedTools: ["ls", "read_file", "glob", "grep", "write_file", "edit_file", "web_fetch", "bash"],
    permissionPolicy: {
      filesystem: "write",
      shell: "limited",
      network: "full",
      deploy: "none",
    },
    toolPermissionRules: {
      bash: DEFAULT_PRESET_BASH_PERMISSION_RULES,
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "reviewer",
    name: "Reviewer",
    description: "审查代码、计划和差异，关注正确性、回归问题和缺失的验证。",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "can-delegate",
    executorType: "ai-sdk",
    systemPrompt: presetAgentSystemPrompts.reviewer,
    capabilities: ["code-review", "risk-analysis", "test-gaps"],
    allowedSubagents: ["explore", "general"],
    allowedTools: ["ls", "read_file", "glob", "grep", "web_fetch", "bash"],
    permissionPolicy: {
      filesystem: "read",
      shell: "limited",
      network: "full",
      deploy: "none",
    },
    toolPermissionRules: {
      bash: DEFAULT_PRESET_BASH_PERMISSION_RULES,
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "writer",
    name: "Writer",
    description: "撰写产品文案、技术文档、规范说明和简洁的用户面向解释。",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "can-delegate",
    executorType: "ai-sdk",
    systemPrompt: presetAgentSystemPrompts.writer,
    capabilities: ["documentation", "copywriting", "summarization"],
    allowedSubagents: ["general"],
    allowedTools: ["ls", "read_file", "glob", "grep", "write_file", "edit_file", "web_fetch", "bash"],
    permissionPolicy: {
      filesystem: "write",
      shell: "limited",
      network: "full",
      deploy: "none",
    },
    toolPermissionRules: {
      bash: DEFAULT_PRESET_BASH_PERMISSION_RULES,
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "planner",
    name: "Planner",
    description: "生成人类可读的计划、权衡分析、风险评估、里程碑和验收检查，不参与运行时编排。",
    tier: "primary",
    origin: "system",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "terminal",
    executorType: "ai-sdk",
    systemPrompt: presetAgentSystemPrompts.planner,
    capabilities: ["planning-advice", "architecture-analysis", "risk-assessment", "acceptance-criteria"],
    allowedSubagents: [],
    allowedTools: ["ls", "read_file", "glob", "grep", "web_fetch", "bash"],
    permissionPolicy: {
      filesystem: "read",
      shell: "limited",
      network: "full",
      deploy: "none",
    },
    toolPermissionRules: {
      bash: DEFAULT_PRESET_BASH_PERMISSION_RULES,
    },
    enabled: true,
    readonly: true,
  },
  {
    id: "opencode",
    name: "OpenCode",
    description: "外部编码智能体入口，为未来通过外部适配器层集成 OpenCode 预留。",
    tier: "primary",
    origin: "external",
    visibility: "visible",
    entryPolicy: "callable",
    delegationPolicy: "terminal",
    executorType: "external-adapter",
    capabilities: ["external-agent", "coding", "workspace"],
    allowedSubagents: [],
    allowedTools: [],
    permissionPolicy: {
      filesystem: "write",
      shell: "limited",
      network: "full",
      deploy: "none",
    },
    external: {
      provider: "opencode",
      workingDirectoryPolicy: "runtime-workspace",
      configDirectoryPolicy: "user-global",
      outputFormat: "event-stream",
    },
    enabled: true,
    readonly: true,
  },
]

