import { createHash } from "node:crypto"
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import type { SqlMigration } from "../src/lib/migrations"

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex")
}

function normalizeSqlForChecksum(sql: string): string {
  return sql.replace(/\r\n?/g, "\n")
}

function toCrlf(sql: string): string {
  return normalizeSqlForChecksum(sql).replace(/\n/g, "\r\n")
}

function getCompatibleChecksums(sql: string, canonicalChecksum: string): string[] | undefined {
  const checksums = new Set<string>()
  checksums.add(sha256(sql))
  checksums.add(sha256(toCrlf(sql)))
  checksums.delete(canonicalChecksum)
  return checksums.size > 0 ? [...checksums].sort() : undefined
}

export async function readPrismaMigrations(migrationsDir: string): Promise<SqlMigration[]> {
  const entries = await readdir(migrationsDir, { withFileTypes: true })
  const migrationNames = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  const migrations: SqlMigration[] = []
  for (const name of migrationNames) {
    const sql = await readFile(join(migrationsDir, name, "migration.sql"), "utf8")
    const checksum = sha256(normalizeSqlForChecksum(sql))
    migrations.push({
      name,
      checksum,
      compatibleChecksums: getCompatibleChecksums(sql, checksum),
      sql,
    })
  }

  return migrations
}

export function renderMigrationManifest(migrations: SqlMigration[]): string {
  return [
    "// This file is generated by hub-server/scripts/migration-manifest.ts. Do not edit by hand.",
    "",
    "import type { SqlMigration } from '../lib/migrations'",
    "",
    `export const PRISMA_MIGRATIONS = ${JSON.stringify(migrations, null, 2)} satisfies SqlMigration[]`,
    "",
  ].join("\n")
}

export async function writeMigrationManifest(options: {
  migrationsDir: string
  outputFile: string
}): Promise<void> {
  const migrations = await readPrismaMigrations(options.migrationsDir)
  await mkdir(dirname(options.outputFile), { recursive: true })
  await writeFile(options.outputFile, renderMigrationManifest(migrations), "utf8")
}
