import { createHash } from "node:crypto"
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import type { SqlMigration } from "../src/lib/migrations"

export async function readPrismaMigrations(migrationsDir: string): Promise<SqlMigration[]> {
  const entries = await readdir(migrationsDir, { withFileTypes: true })
  const migrationNames = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  const migrations: SqlMigration[] = []
  for (const name of migrationNames) {
    const sql = await readFile(join(migrationsDir, name, "migration.sql"), "utf8")
    migrations.push({
      name,
      checksum: createHash("sha256").update(sql).digest("hex"),
      sql,
    })
  }

  return migrations
}

export function renderMigrationManifest(migrations: SqlMigration[]): string {
  return [
    "// This file is generated by hub-server/scripts/migration-manifest.ts. Do not edit by hand.",
    "",
    "import type { SqlMigration } from '../lib/migrations'",
    "",
    `export const PRISMA_MIGRATIONS = ${JSON.stringify(migrations, null, 2)} satisfies SqlMigration[]`,
    "",
  ].join("\n")
}

export async function writeMigrationManifest(options: {
  migrationsDir: string
  outputFile: string
}): Promise<void> {
  const migrations = await readPrismaMigrations(options.migrationsDir)
  await mkdir(dirname(options.outputFile), { recursive: true })
  await writeFile(options.outputFile, renderMigrationManifest(migrations), "utf8")
}
